### PR TITLE
feat: added hyperbolic llm models

### PR DESCRIPTION
**Pull request by Ahmed-Rahil**
Screenshot 2024-12-29 142806

### CODE REVIEW

**Comment by adam2am** [comment]
Deepseek v3 is also accessible via api, they showed it on twitter, but the hasn’t updated on their website yet. I guess it's unstable or smth

**Comment by thecodacus** [comment]
thanks for adding this @Ahmed-Rahil, looks good to me.
Does hyperbolic  support dynamic model list?
if yes will you be adding that ?
you can check the togatherai provider for reference.

**Comment by wonderwhy-er** [comment]
I just tested, seems to work, was bit confusing to get API key, their website is little bit weird

They do not mention API to get model list in
https://docs.hyperbolic.xyz/docs/rest-api

But calling this worked:
curl -X GET "https://api.hyperbolic.xyz/v1/models" -H "Authorization: Bearer apiKey"

And returned this for me:
`{"object":"list","data":[{"id":"Qwen/Qwen2.5-72B-Instruct","created":1735562231,"object":"model","owned_by":"Hyperbolic","number_of_inference_nodes":null,"supports_chat":false,"supports_image_input":false,"supports_tools":false,"context_length":null},{"id":"Qwen/Qwen2-VL-72B-Instruct","created":1735562231,"object":"model","owned_by":"Hyperbolic","number_of_inference_nodes":null,"supports_chat":false,"supports_image_input":false,"supports_tools":false,"context_length":null},{"id":"meta-llama/Meta-Llama-3.1-70B-Instruct","created":1735562231,"object":"model","owned_by":"Hyperbolic","number_of_inference_nodes":null,"supports_chat":true,"supports_image_input":false,"supports_tools":false,"context_length":32768},{"id":"Qwen/QwQ-32B-Preview","created":1735562231,"object":"model","owned_by":"Hyperbolic","number_of_inference_nodes":null,"supports_chat":false,"supports_image_input":false,"supports_tools":false,"context_length":null},{"id":"Qwen/Qwen2-VL-7B-Instruct","created":1735562231,"object":"model","owned_by":"Hyperbolic","number_of_inference_nodes":null,"supports_chat":false,"supports_image_input":false,"supports_tools":false,"context_length":null},{"id":"meta-llama/Llama-3.3-70B-Instruct","created":1735562231,"object":"model","owned_by":"Hyperbolic","number_of_inference_nodes":null,"supports_chat":false,"supports_image_input":false,"supports_tools":false,"context_length":null},{"id":"meta-llama/Llama-3.2-3B-Instruct","created":1735562231,"object":"model","owned_by":"Hyperbolic","number_of_inference_nodes":null,"supports_chat":false,"supports_image_input":false,"supports_tools":false,"context_length":null},{"id":"FLUX.1-dev","created":1735562231,"object":"model","owned_by":"Hyperbolic","number_of_inference_nodes":null,"supports_chat":false,"supports_image_input":true,"supports_tools":false,"context_length":null},{"id":"StableDiffusion","created":1735562231,"object":"model","owned_by":"Hyperbolic","number_of_inference_nodes":null,"supports_chat":false,"supports_image_input":true,"supports_tools":false,"context_length":null},{"id":"meta-llama/Meta-Llama-3.1-8B-Instruct","created":1735562231,"object":"model","owned_by":"Hyperbolic","number_of_inference_nodes":null,"supports_chat":true,"supports_image_input":false,"supports_tools":false,"context_length":32768},{"id":"deepseek-ai/DeepSeek-V2.5","created":1735562231,"object":"model","owned_by":"Hyperbolic","number_of_inference_nodes":null,"supports_chat":false,"supports_image_input":false,"supports_tools":false,"context_length":null},{"id":"meta-llama/Meta-Llama-3-70B-Instruct","created":1735562231,"object":"model","owned_by":"Hyperbolic","number_of_inference_nodes":null,"supports_chat":true,"supports_image_input":false,"supports_tools":false,"context_length":32768},{"id":"meta-llama/Meta-Llama-3.1-405B-FP8","created":1735562231,"object":"model","owned_by":"Hyperbolic","number_of_inference_nodes":null,"supports_chat":true,"supports_image_input":false,"supports_tools":false,"context_length":32768},{"id":"meta-llama/Meta-Llama-3.1-405B-Instruct","created":1735562231,"object":"model","owned_by":"Hyperbolic","number_of_inference_nodes":null,"supports_chat":true,"supports_image_input":false,"supports_tools":false,"context_length":32768},{"id":"deepseek-ai/DeepSeek-V3","created":1735562231,"object":"model","owned_by":"Hyperbolic","number_of_inference_nodes":null,"supports_chat":false,"supports_image_input":false,"supports_tools":false,"context_length":null},{"id":"NousResearch/Hermes-3-Llama-3.1-70B","created":1735562231,"object":"model","owned_by":"Hyperbolic","number_of_inference_nodes":null,"supports_chat":true,"supports_image_input":false,"supports_tools":false,"context_length":12000},{"id":"meta-llama/Meta-Llama-3.1-405B","created":1735562231,"object":"model","owned_by":"Hyperbolic","number_of_inference_nodes":null,"supports_chat":false,"supports_image_input":false,"supports_tools":false,"context_length":null},{"id":"mistralai/Pixtral-12B-2409","created":1735562231,"object":"model","owned_by":"Hyperbolic","number_of_inference_nodes":null,"supports_chat":false,"supports_image_input":false,"supports_tools":false,"context_length":null},{"id":"Qwen/Qwen2.5-Coder-32B-Instruct","created":1735562231,"object":"model","owned_by":"Hyperbolic","number_of_inference_nodes":null,"supports_chat":false,"supports_image_input":false,"supports_tools":false,"context_length":null},{"id":"meta-llama/Meta-Llama-3.1-405B-Instruct-Virtuals","created":1735562231,"object":"model","owned_by":"Hyperbolic","number_of_inference_nodes":null,"supports_chat":false,"supports_image_input":false,"supports_tools":false,"context_length":null}]}`


Problem is that it requires auth key 
If I call just:
curl -X GET "https://api.hyperbolic.xyz/v1/models"     

It returns:
{"detail":"Not authenticated"}

I am not sure we support authorised dynamic mode lists yet

**Comment by thecodacus** [comment]
> I am not sure we support authorised dynamic mode lists yet

we do, the togather ai is doing that

**Comment by Ahmed-Rahil** [comment]
yes , let me try adding  hyperbolic  dynamic model list.

**Comment by Ahmed-Rahil** [comment]
able to return the dynamic model list but , the models fetched dynamically are not reflecting on the ui. need help!!
Screenshot 2024-12-30 214937

**Comment by juanmcampos** [comment]
Did you try reloading the browser?  

For what I can tell initializeModelList({}); and getDynamicModels are requested at load only and wont update only by changing the select. I made a change on mine to have the list requested on change. Maybe I can do a PR after cleaning up my code a little.

**Comment by wonderwhy-er** [comment]
with npm run dev seems to work for me
image

If key was already set, os yeah, may be you need to refresh after setting they key for the first time

Something that can be fixed separately

**Comment by thecodacus** [comment]
> For what I can tell initializeModelList({}); and getDynamicModels

actually initializeModelList also gets loaded on runtime with UI api keys once the UI gets loaded.
its in the base chat component

**Comment by thecodacus** [comment]
> If key was already set, os yeah, may be you need to refresh after setting they key for the first time

yrs if the keys were set in UI the you need to refresh

**Comment by Ahmed-Rahil** [comment]
yeah, got it!! Thanks.

**Comment by thecodacus** [comment]
looks good to me, just remove the log and we can merge it

**Comment by Ahmed-Rahil** [comment]
done. logs removed!!

**Comment by wonderwhy-er** [comment]
I just made separate PR to reload model list without page refresh on API keys change
https://github.com/stackblitz-labs/bolt.diy/pull/944
Bit suboptimal 
But as API keys do not change often should be okey

**Pull request merged**
