### PR TITLE
(Work In Progress) Exploration of how to show token usage

### PR DESCRIPTION
**Pull request by wonderwhy-er**
This PR adds the ability to show token usage in messages for enhanced transparency and monitoring of API consumption. 
The key features include:
Token Usage Display: Display token count for input and output in each message.

Technical implementation and exploration:
- First I tried to use on onFinished options.usage in [Chat.client.tsx](https://github.com/stackblitz-labs/bolt.diy/pull/609/files#diff-c3e814ea52016b5a6aa549d4a1b89d306c9ac276ba0f79a956dba166e6c84b09R126) 
- But above does not work, returns NaNs, I could not figure out why and how to fix. Could be issue with Vercel client or how Bolt uses Verce ai on server with custom switchble stream streams
- Then I looked in to [data streams](https://sdk.vercel.ai/docs/ai-sdk-ui/streaming-data)
- That did not work aether...
- Next I tried returning them in text, as bolt actions and arrived at current implementation

Its bit hackish but hard to get to better variant in reasonable amount of time, may be someone can come later and improve better than I could.
image

### CODE REVIEW

**Comment by pjmartorell** [comment]
Which LLM are you using to test it? As far as a I know your approach correspond to OpenAI models only. Also I think that the request must contain a `stream_options: {"include_usage": true}`parameter in order to make the API return the `usage`object (see https://platform.openai.com/docs/api-reference/chat/streaming#chat/streaming-usage).

**Comment by thecodacus** [comment]
this should work
image

**Comment by thecodacus** [comment]
nah, its  returning nan

**Comment by wonderwhy-er** [comment]
> @wonderwhy-er Which LLM are you using to test it? As far as a I know your approach correspond to OpenAI models only. Also I think that the request must contain a `stream_options: {"include_usage": true}`parameter in order to make the API return the `usage`object (see https://platform.openai.com/docs/api-reference/chat/streaming#chat/streaming-usage).

It may not work with all providers but google and openai 100% return it
But something is of in how bolt is setup
Server in onFinish does get usage
But client does not
I am not sure how to fix that, have not found anything
Instead I will pass server usage stats to client for now
image

I also just tested Antropic, OpenRouter, Cohere, Together -  and they work.

Test Groq, HuggingFace and for them it does not work.

So, initially it will work only for some providers.

**Comment by wonderwhy-er** [comment]
> nah, its returning nan

On client yet. On server depending on the provider it does return.
I think it will solve itself if we move API calls to client like discussed on Saturday, but for now I will return server responses to client.
And show them if they are not NaN.
Will serve as a way to test context use optimisations.

**Comment by thecodacus** [comment]
if we move the llm call to client, can we still use the vercel's AI sdk. its very easy but also not restricted

**Comment by wonderwhy-er** [comment]
Vercel SDK works on client too. I tested it against LM studio and it worked.
Not sure yet, will need to start work on it first.

I will start by moving LM Studio call to client, then ollama.
Then we can see with other popular providers.

**Comment by thecodacus** [comment]
I suggest using this approach, it will automatically get appended to the assistant message and can be used without any regex parsing

```
if (usage) {
  cumulativeUsage.completionTokens += usage.completionTokens || 0;
  cumulativeUsage.promptTokens += usage.promptTokens || 0;
  cumulativeUsage.totalTokens += usage.totalTokens || 0;
  
  return stream.switchSource(createDataStream({
    async execute(dataStream) {
      dataStream.writeMessageAnnotation({
        type: 'usage', value: {
          completionTokens: cumulativeUsage.completionTokens,
          promptTokens: cumulativeUsage.promptTokens,
          totalTokens: cumulativeUsage.totalTokens,
        } });
    },
    onError: (error: any) => `Custom error: ${error.message}`,
  })).then(()=>{
    stream.close()
  })
}

```

the output looks like this 
image

**Comment by dustinwloring1988** [comment]
Same error as above on Windows 11 except I am able to see the token usage in the terminal.

https://github.com/user-attachments/assets/454e4869-2a8f-4dd4-a46f-6c691db0f66a

**Pull request merged**
