### PR TITLE
feat: Add chat history backup and restore functionality"

### PR DESCRIPTION
**Pull request by sidbetatester**
Added chat history backup and restore functionality:

- Added export button to download chat history as JSON
- Added import button to restore chat history from backup
- Added proper error handling and user feedback
- Implemented version checking and data validation
- Added logging for debugging

### Export Chat History
1. Look for the download icon (↓) next to "Your Chats" in the sidebar
2. Click the icon to download your chat history
3. A JSON file named `bolt-chat-history-[date].json` will be downloaded
4. You'll see a success notification when the export is complete

### Import Chat History
1. Look for the upload icon (↑) next to "Your Chats" in the sidebar
2. Click the icon to open the file picker
3. Select a previously exported JSON backup file
4. The page will automatically reload after successful import
5. You'll see your imported chats in the sidebar

## Technical Changes
- Modified Menu.client.tsx to add import/export buttons
- Used existing persistence layer for data handling
- Added user feedback via toast notifications
- Implemented proper error handling and validation

## Error Handling
- Shows error messages if:
  - File format is invalid
  - Database is not initialized
  - File reading fails
  - Import/export operation fails

## Notes
- The page will reload after successful import to show the restored chats
- All existing chats are preserved during import
- Exported files include version information for future compatibility

Chat_history_backup_restore

### CODE REVIEW

**Comment by sidbetatester** [comment]
This is a simple feature to backup the projects, mainly helpful if you need to clear browser history and restore on the same system, or to take it around different systems. I kept the changes very minimal to not affect any existing code.

**Comment by sidbetatester** [comment]
@coleam00 Who can take care of the workflow approval?

**Comment by wonderwhy-er** [comment]
Was thinking to add this too, but do it per one chat, not all of them
Though I guess doing it for all of them is good too, will review now

**Comment by wonderwhy-er** [comment]
1. Something broken around deleting chats, there is not item and description. Try to delete a chat

2. I also think that you need to split that large function in to smaller parts. Harder to understand what it does.

3. There were couple of typescheck issues when I runned workflows

4. Also there is empty app/utils/backup.ts file?

**Comment by coleam00** [comment]
@sidbetatester Could you reply to @wonderwhy-er feedback when you get the chance? Thanks for that by the way Eduard!

**Comment by sidbetatester** [comment]
@coleam00 Thanks for the follow-up! Hope you all had a wonderful Thanksgiving holiday!

Hi Eduard (@wonderwhy-er),

Sorry I was a little busy the last couple of weeks and couldn't respond sooner. Thank you for the review and feedback. I just downloaded the latest main branch and see a lot of improvements. It seems like someone was kind enough to clean up the conflicts and incorporate the improvements suggested above, and it looks a lot more polished now! What should we do now? Is there anything else you need me to do?

**Comment by thecodacus** [comment]
can you resolve this conflicts, I will review and merge

**Comment by sidbetatester** [comment]
Hi Anirban @thecodacus 
The conflicts must be resolved now, can you verify please.

**Comment by sidbetatester** [comment]
continuing in https://github.com/stackblitz-labs/bolt.diy/pull/871

**Pull request closed without merging**
