### PR TITLE
Add Screenshot Capture and Management Features to Chat and Workbench Components

### PR DESCRIPTION
**Pull request by emcconnell**
This pull request introduces a new feature that allows users to take screenshots within the chat and workbench components. The most important changes include adding the `ScreenshotStateManager` and `ScreenshotSelector` components, and updating the `BaseChat` and `Preview` components to integrate these new functionalities.

New Components:

* [`app/components/chat/ScreenshotStateManager.tsx`](diffhunk://#diff-e0f891c98f6b77a0a29028be3227f8069bb6ad49a8f407cce57c7c784c5f9314R1-R33): Added `ScreenshotStateManager` component to manage the state of screenshots in the chat.
* [`app/components/workbench/ScreenshotSelector.tsx`](diffhunk://#diff-0894b7f75cc05ed6651b73e3ee4458431d9681cf3383f1434348560d0412cbe8R1-R265): Added `ScreenshotSelector` component to handle the screenshot selection process in the workbench.

Integration with Existing Components:

* [`app/components/chat/BaseChat.tsx`](diffhunk://#diff-a87a7f7c69d4bc6518b70a4fa3122ede18e570da15f12975804a87eac181c700R28): Imported and integrated `ScreenshotStateManager` into the `BaseChat` component to handle screenshot-related state. [[1]](diffhunk://#diff-a87a7f7c69d4bc6518b70a4fa3122ede18e570da15f12975804a87eac181c700R28) [[2]](diffhunk://#diff-a87a7f7c69d4bc6518b70a4fa3122ede18e570da15f12975804a87eac181c700R380-R389)
* [`app/components/workbench/Preview.tsx`](diffhunk://#diff-9673a52413c9a3b41c86eb5fc611675af37ae826eba67c350ccb233ba68e0eeeR6): Imported and integrated `ScreenshotSelector` into the `Preview` component to enable screenshot selection mode. [[1]](diffhunk://#diff-9673a52413c9a3b41c86eb5fc611675af37ae826eba67c350ccb233ba68e0eeeR6) [[2]](diffhunk://#diff-9673a52413c9a3b41c86eb5fc611675af37ae826eba67c350ccb233ba68e0eeeR19) [[3]](diffhunk://#diff-9673a52413c9a3b41c86eb5fc611675af37ae826eba67c350ccb233ba68e0eeeR83-R93) [[4]](diffhunk://#diff-9673a52413c9a3b41c86eb5fc611675af37ae826eba67c350ccb233ba68e0eeeL117-R132)

Longer video, but the shorter one below is prob. enough to get the idea: https://www.youtube.com/watch?v=cJsZVsswWnI

https://github.com/user-attachments/assets/c076121c-7866-4cdc-b05b-1d595582a1fa

### CODE REVIEW

**Comment by thecodacus** [comment]
this is so cool

**Comment by Stijnus** [comment]
Nice job , i was also working on this a few days back. Just tested the code and looks good, i will test some more in a couple of days if work let me... Keep you posted.

Anyway great job :)

**Comment by VersaceXcodes** [comment]
instead of manual, can it be done in the code? like it auto takes screenshot of preview instead from users side ?

**Comment by emcconnell** [comment]
> instead of manual, can it be done in the code? like it auto takes screenshot of preview instead from users side ?

@VersaceXcodes it could be if you wanted the system to check a result, automated, or something similar. The purpose of this feature, though, is to target a specific area of the app being built visually to augment the prompt. If you haven't watched the longer linked YouTube video maybe check that out. Thanks for the input though!

**Comment by emcconnell** [comment]
I just merged main so this can go. New video with main merged below. If we like the feature, can I get an official thumbs up and I or anyone can merge it ;) If any issue, let me know. Thanks!

@coleam00 @thecodacus @wonderwhy-er 


https://github.com/user-attachments/assets/106af687-f0b0-4558-b2cd-c29f4678a6f4

**Comment by dustinwloring1988** [comment]
@emcconnell looks nice and integrates well. Saving a few steps from using the snipping tool

**Comment by wonderwhy-er** [comment]
Hm, I wonder if it would have been easier to send it html/css instead of image.
Should be easier for it to understand(may be, especially if there are IDs) and cheaper in tokens than sending a screenshot. 
But sometimes screenshot is better.

**Comment by thecodacus** [comment]
> Hm, I wonder if it would have been easier to send it html/css instead of image. Should be easier for it to understand(may be, especially if there are IDs) and cheaper in tokens than sending a screenshot. But sometimes screenshot is better.

maybe we can have variation for this, like inspect mode in chrome. which will get the html and sent it instead of image

**Comment by emcconnell** [comment]
@wonderwhy-er @thecodacus 

I like the idea of also having an inspect feature to add targeted context and did think about it. I went with the image clip b/c it seemed more intuitive for a non-developer to use, and for now image might hit more use cases. I am still interested in dev tool inspect. I am also generally interested in the area of functional UI/UX with the product. I've been thinking of various ideas in this vein.

**Pull request merged**
