### PR TITLE
feat: added perplexity models

### PR DESCRIPTION
**Pull request by meetpateltech**
Perplexity Integration

### CODE REVIEW

**Comment by bestfriendai** [comment]
could you make it so that it only uses perplexity for web search?

**Comment by chrismahoney** [comment]
Tagging to cover with #276 post provider refactor.

**Comment by thecodacus** [comment]
@meetpateltech can you resolve the conflicts, I can then test and merge this

**Comment by meetpateltech** [comment]
@thecodacus This PR was closed automatically due to a force merge with the main branch. I’ve created a new one with the same integration, now without any conflicts. Please test and merge!

New PR #715

**Pull request closed without merging**
