### PR TITLE
doc: update README.md

### PR DESCRIPTION
**Pull request by dustinwloring1988**
image

### CODE REVIEW

**Comment by goldn-ky-ndm** [comment]
Might be good to provide instructions on how to update the application and sync with current git version in the future since this project does change pretty frequently.

I usually just do these steps

Git status 

if there are existing changes, I do 
    git stash
if no existing changes
    git pull origin main 
 
pnpm install

pnpm dev

**Comment by dustinwloring1988** [comment]
@goldn-ky-ndm you are correct I will add it, thank you.

**Comment by marcojsmith** [comment]
Thank you, looks much better than the current.

Could you also add in what Dev vs Prod is, and which one to use?
And then maybe also how to switch it off?

Thanks again.

**Comment by dustinwloring1988** [comment]
@marcojsmith good idea but I want o hold off on that for this PR and in the next one as I was thinking of making the production build a separate part.

**Pull request merged**
