### PR TITLE
Fix Multiple Issues: Page Load Speed, API Key Settings, Model Selection, and Sidebar Behavior

### LINKED ISSUE #451: ollama model specification does not take effect
### Describe the bug

APICallError [AI_APICallError]: Not Found
    at /data/bolt.new-any-llm/node_modules/.pnpm/@ai-sdk+provider-utils@1.0.20_zod@3.23.8/node_modules/@ai-sdk/provider-utils/dist/index.js:505:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async postToApi (/data/bolt.new-any-llm/node_modules/.pnpm/@ai-sdk+provider-utils@1.0.20_zod@3.23.8/node_modules/@ai-sdk/provider-utils/dist/index.js:398:28)
    at async OllamaChatLanguageModel.doStream (/data/bolt.new-any-llm/node_modules/.pnpm/ollama-ai-provider@0.15.2_zod@3.23.8/node_modules/ollama-ai-provider/dist/index.js:485:50)
    at async fn (file:///data/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:3938:23)
    at async file:///data/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:256:22
    at async _retryWithExponentialBackoff (file:///data/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:86:12)
    at async startStep (file:///data/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:3903:13)
    at async fn (file:///data/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:3977:11)
    at async file:///data/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:256:22
    at async chatAction (/data/bolt.new-any-llm/app/routes/api.chat.ts:64:20)
    at async Object.callRouteAction (/data/bolt.new-any-llm/node_modules/.pnpm/@remix-run+server-runtime@2.10.0_typescript@5.5.2/node_modules/@remix-run/server-runtime/dist/data.js:37:16)
    at async /data/bolt.new-any-llm/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:4612:21
    at async callLoaderOrAction (/data/bolt.new-any-llm/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:4677:16)
    at async Promise.all (index 1)
    at async callDataStrategyImpl (/data/bolt.new-any-llm/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:4552:17)
    at async callDataStrategy (/data/bolt.new-any-llm/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:4041:19)
    at async submit (/data/bolt.new-any-llm/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:3900:21)
    at async queryImpl (/data/bolt.new-any-llm/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:3858:22)
    at async Object.queryRoute (/data/bolt.new-any-llm/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:3827:18)
    at async handleResourceRequest (/data/bolt.new-any-llm/node_modules/.pnpm/@remix-run+server-runtime@2.10.0_typescript@5.5.2/node_modules/@remix-run/server-runtime/dist/server.js:413:20)
    at async requestHandler (/data/bolt.new-any-llm/node_modules/.pnpm/@remix-run+server-runtime@2.10.0_typescript@5.5.2/node_modules/@remix-run/server-runtime/dist/server.js:156:18)
    at async /data/bolt.new-any-llm/node_modules/.pnpm/@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge/node_modules/@remix-run/dev/dist/vite/cloudflare-proxy-plugin.js:70:25 {
  cause: undefined,
  url: 'http://10.88.7.222:11434/api/chat',
  requestBodyValues: {
    format: undefined,
    model: 'claude-3-5-sonnet-latest',
    options: { num_ctx: 6144, num_predict: 8000, temperature: 0 },
    messages: [ [Object], [Object] ],
    tools: undefined
  },
  statusCode: 404,
  responseHeaders: {
    'content-length': '78',
    'content-type': 'application/json; charset=utf-8',
    date: 'Fri, 29 Nov 2024 09:15:26 GMT'
  },
  responseBody: '{"error":"model \\"claude-3-5-sonnet-latest\\" not found, try pulling it first"}',
  isRetryable: false,
  data: undefined,
  [Symbol(vercel.ai.error)]: true,
  [Symbol(vercel.ai.error.AI_APICallError)]: true

### Link to the Bolt URL that caused the error

10.88.7.222:11434

### Steps to reproduce

Use directly after startup

### Expected behavior

1

### Screen Recording / Screenshot

_No response_

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

_No response_

### LINKED ISSUE #532: There was an error processing your request: No details were returned
### Describe the bug

When running the library bolt.new-any-llm in a Docker environment and attempting to input a value in the chat, the following error occurs:
image
All necessary API keys have been provided in the following locations:

.env.local file.
docker-compose.yaml file.
Model settings in the client configuration.

### Link to the Bolt URL that caused the error

r

### Steps to reproduce

Steps to Reproduce:
Clone the bolt.new-any-llm repository.
Ensure the following versions are installed:
Node.js: v23.3.0
Docker: 27.3.1, build ce12230
Docker Compose: v2.30.3-desktop.1
Git: 2.47.1.windows.1
OS: Windows 10
Add all required API keys in the following locations:
.env.local file.
docker-compose.yaml file.
Model settings in the client.

Start the application using Docker:
docker-compose --profile development up

### Expected behavior

The chat should process the input and return the corresponding response without errors.

### Screen Recording / Screenshot

_No response_

### Platform

OS: Windows 10
Node.js: v23.3.0
Docker: 27.3.1, build ce12230
Docker Compose: v2.30.3-desktop.1
Git: 2.47.1.windows.1

### Provider Used

_No response_

### Model Used

_No response_

### Additional context

_No response_

### LINKED ISSUE #539: Integeration with LMStudio and Ollama is not working
### Describe the bug

I got this error when i try to use LM Studio or Ollama

### Link to the Bolt URL that caused the error

localhost

### Steps to reproduce

1-0Select Ollama or LM Studio 
Select the Model you have from the lit
Write your prompt then submit

### Expected behavior

it muust give me response

### Platform

- OS:  Wiindows
- Browser: Chrome

### Provider Used

_No response_

### Model Used

_No response_

### Additional context

_No response_

### LINKED ISSUE #551: model: 'claude-3-5-sonnet-latest', - error -   [Symbol(vercel.ai.error.AI_RetryError)]: true
### Describe the bug

bolt.new-any-llm app error when running the local 
setting somewhere that is stuck on anthropic as default LLM, doesn't switch to Ollama even when selected in the webgui dropdown  try to chat. I do have Windsurf and Cline installed but both are disabled in workspace. 
[https://ibb.co/C8gXNQ8](url)

### Link to the Bolt URL that caused the error

https://github.com/coleam00/bolt.new-any-llm

### Steps to reproduce

pnpm run dev
select Ollama from dropdown webgui
select qwen2.5-coder:14b
begin chat
error 
https://ibb.co/C8gXNQ8

### Expected behavior

app switches to ollama for LLM 

### Screen Recording / Screenshot

 url: 'http://localhost:11434/api/chat',
      requestBodyValues: [Object],
      statusCode: undefined,
      responseHeaders: undefined,
      responseBody: undefined,
      isRetryable: true,
      data: undefined,
      [Symbol(vercel.ai.error)]: true,
      [Symbol(vercel.ai.error.AI_APICallError)]: true
2024-12-05 06_56_08-Extension_ Cline (prev  Claude Dev) - bolt new-any-llm - Visual Studio Code

https://ibb.co/C8gXNQ8

### Platform

- OS: windows 11 pro
- Ollama is running
- cline disabled in workspace
- docker disabled in workspace
- 

### Provider Used

_No response_

### Model Used

Ollama gwen2.5-coder:14b

### Additional context

_No response_

### LINKED ISSUE #558: problem with ollama models
### Describe the bug

ollama is corrctly configured, running, and no chat probleme were reported using the console prompt
ollama.api wroking correctly with packet sender
ollama is selected in Bolt ai chat web pages
one of my ollama (qwen2.5-coder:0.5b (494.03M)) model is selected (!!! i have same probleme with other models)
but i have the following error on my terminal

```sh
APICallError [AI_APICallError]: Not Found
    at C:\Users\HP\source\repos\LLMs\Bolt\node_modules\.pnpm\@ai-sdk+provider-utils@1.0.20_zod@3.23.8\node_modules\@ai-sdk\provider-utils\src\response-handler.ts:72:16
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at postToApi (C:\Users\HP\source\repos\LLMs\Bolt\node_modules\.pnpm\@ai-sdk+provider-utils@1.0.20_zod@3.23.8\node_modules\@ai-sdk\provider-utils\src\post-to-api.ts:81:28)
    at OllamaChatLanguageModel.doStream (C:\Users\HP\source\repos\LLMs\Bolt\node_modules\.pnpm\ollama-ai-provider@0.15.2_zod@3.23.8\node_modules\ollama-ai-provider\src\ollama-chat-language-model.ts:230:50)
    at fn (file:///C:/Users/HP/source/repos/LLMs/Bolt/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/generate-text/stream-text.ts:378:23)        
    at file:///C:/Users/HP/source/repos/LLMs/Bolt/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/telemetry/record-span.ts:18:22
    at _retryWithExponentialBackoff (file:///C:/Users/HP/source/repos/LLMs/Bolt/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.7.2__zod@3.23.8/node_modules/ai/util/retry-with-exponential-backoff.ts:37:12)
    at startStep (file:///C:/Users/HP/source/repos/LLMs/Bolt/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/generate-text/stream-text.ts:333:13) 
    at fn (file:///C:/Users/HP/source/repos/LLMs/Bolt/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/generate-text/stream-text.ts:414:11)        
    at file:///C:/Users/HP/source/repos/LLMs/Bolt/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/telemetry/record-span.ts:18:22
    at chatAction (C:/Users/HP/source/repos/LLMs/Bolt/app/routes/api.chat.ts:65:20)
    at Object.callRouteAction (C:\Users\HP\source\repos\LLMs\Bolt\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\data.js:36:16)
    at C:\Users\HP\source\repos\LLMs\Bolt\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4899:19
    at callLoaderOrAction (C:\Users\HP\source\repos\LLMs\Bolt\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4963:16)
    at async Promise.all (index 0)
    at defaultDataStrategy (C:\Users\HP\source\repos\LLMs\Bolt\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4772:17)
    at callDataStrategyImpl (C:\Users\HP\source\repos\LLMs\Bolt\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4835:17)
    at callDataStrategy (C:\Users\HP\source\repos\LLMs\Bolt\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3992:19)
    at submit (C:\Users\HP\source\repos\LLMs\Bolt\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3755:21)
    at queryImpl (C:\Users\HP\source\repos\LLMs\Bolt\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3684:22)
    at Object.queryRoute (C:\Users\HP\source\repos\LLMs\Bolt\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3629:18)
    at handleResourceRequest (C:\Users\HP\source\repos\LLMs\Bolt\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:402:20)
    at requestHandler (C:\Users\HP\source\repos\LLMs\Bolt\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:156:18)
    at C:\Users\HP\source\repos\LLMs\Bolt\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_zyxju6yjkqxopc2lqyhhptpywm\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:70:25 {
  cause: undefined,
  url: 'http://127.0.0.1:11434/api/chat',
  requestBodyValues: {
    format: undefined,
    model: 'gpt-4o-mini',
    options: { num_ctx: 32768, num_predict: 8000, temperature: 0 },
    messages: [ [Object], [Object] ],
    tools: undefined
  },
  statusCode: 404,
  responseHeaders: {
    'content-length': '65',
    'content-type': 'application/json; charset=utf-8',
    date: 'Thu, 05 Dec 2024 21:01:25 GMT'
  },
  responseBody: '{"error":"model \\"gpt-4o-mini\\" not found, try pulling it first"}',
  isRetryable: false,
  data: undefined,
  [Symbol(vercel.ai.error)]: true,
  [Symbol(vercel.ai.error.AI_APICallError)]: true
}
```

### Link to the Bolt URL that caused the error

local

### Steps to reproduce

1) download bolt from this repo
2) extract it to your location
3) `$> pnpm install `
5) download ollama
6) $>ollama --version
7) `$> ollama run qwen2.5-coder:0.5b`
8) go to bolt file .env.local and set `OLLAMA_API_BASE_URL=http://127.0.0.1:11434`

### Expected behavior

no error

### Screen Recording / Screenshot

Capture

### Platform

- OS:W10
- Browser: Chrome
- npm version : 10.5.2
- pnpm version : 9.14.4
- ollama version : 0.4.7

### Provider Used

ollama

### Model Used

qwen2.5-coder:0.5b (494.03M)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by System233**
**Summary of Changes for This PR:**  
1. **Fixed slow page loading:** 
Resolved an issue where refreshing the page under poor network conditions caused the dynamic model list to be fetched each time, leading to a white screen for over ten seconds.  
2. **Fixed API Key setting issues:** 
Addressed a bug where API Key settings on the page were often ineffective with providers like OpenAILike. Even after setting a new API Key, conversations continued using the old one.  This is because the update of the child component has no effect on the parent component's useEffect
3. **Fixed invalid model selection:**
 Corrected issues where switching the model provider did not update the model selection. Additionally, when the server-side model list was out of sync with the client, the server would arbitrarily default to using the "claude-3-5-sonnet-latest" model for requests without informing the user, resulting in discrepancies with the model displayed in the Web UI.
4. **Fixed sidebar annoyance:** 
Adjusted the behavior of the sidebar, which frequently expanded when the mouse moved near it. It now only expands when the sidebar button is clicked.  
> Added an expand/collapse event to the sidebar icon on the right side of the top Bolt logo. The original sidebar icon had no functionality. Now, users can manually expand or collapse the sidebar by clicking the icon, preventing the sidebar from expanding frequently when the mouse moves near it during chat input on the left side.

5. Fully implemented dynamic model parameter passing, eliminating the synchronization issues between front-end and back-end model parameters.  
> The original implementation had both the server and client maintain their own copies of the MODEL LIST, which had the following drawbacks:  
> 1. The client's MODEL LIST is not sourced from the server, and when the user sets the API KEY, the client's MODEL LIST changes.  
> 2. When the server pulls the MODEL LIST, it can only use the API KEY set in the environment.  
> 3. The server cannot recognize new models coming from the client.
6. Passed API key, model, and other information through the request body, removing hidden `[Model:]` and `[Provider:]` directives, enhancing reliability.
> The original API KEY, model settings, and other parameter passing were very disorganized. API keys for all providers were passed in the request body, API keys were also fetched from cookies, and hidden directives like [MODEL:] were inserted into user input. This approach significantly increased unreliability.
> 
> Now, API KEY and model parameters are uniformly passed through the request body, while the provider remains the same as before, meaning dynamic providers are not supported. The advantage of this approach is that, in the future, users can add custom MODEL lists and modify model parameters on the client side without needing to modify the server-side code or restart the server.

Fixes #532, fixes #539, fixes #551 , fixes  #451, fixes #558

### CODE REVIEW

**Comment by System233** [comment]
I stuck with Bolt for several days and even fixed a ton of serious bugs for it.   
Yet today, Cline took me away in just five minutes and showed me the truly correct path.

**Comment by System233** [comment]
I no longer use bolt, so these merge conflicts will not be resolved, keep these errors intact.

**Comment by sid-newby** [comment]
cline blew my fucking mind today too.

**Comment by System233** [comment]
> cline blew my fucking mind today too.

Yes, cline is like a dimensional reduction strike against Bolt.

**Pull request closed without merging**
