### PR TITLE
feat(experimental): Add Configurable System Prompts Feature

### PR DESCRIPTION
**Pull request by thecodacus**
# Add Configurable System Prompts Feature

## Overview
This PR introduces a dynamic system prompt configuration feature that allows users to select different LLM system prompts based on their needs. This enhancement provides flexibility in how the AI assistant behaves and processes requests, with initial testing showing promising results across models including GPT-4 and Claude 2.5 Coder 32k.

### 1. Prompt Library Implementation
- Added new `PromptLibrary` class to manage different system prompts
- Implemented two initial prompts:
  - Default: The battle-tested standard system prompt
  - Optimized: An experimental version designed for lower token usage
- Created extensible architecture for future prompt additions

### 2. Settings Integration
- Added prompt selection UI in the Features tab
- Implemented prompt persistence using cookies
- Added new `promptId` state management in settings store

### 3. Backend Integration
- Modified chat API to support dynamic prompt selection
- Updated stream text functionality to incorporate selected prompts
- Maintained backward compatibility with existing chat functionality

### 4. File Structure Updates
- Moved prompts to a dedicated directory under `lib/common/prompts/`
- Created new `optimized.ts` for the experimental prompt version
- Reorganized prompt-related utilities for better maintainability

### Prompt Library Structure
The `PromptLibrary` class provides:
- Centralized prompt management
- Type-safe prompt registration and retrieval
- Configurable prompt options (working directory, HTML elements, etc.)
- Easy extensibility for adding new prompts

### Settings Integration
- New `promptStore` atom in settings store
- Persistent storage using cookies
- UI integration in Features tab with dropdown selection
- Real-time prompt switching without page reload

## Testing Results
- Tested with GPT-4 and Claude 2.5 Coder 32k
- Optimized prompt showed improved performance in token usage
- Maintained response quality across different models
- Verified prompt persistence across sessions

## Migration Impact
- No breaking changes to existing functionality
- Default prompt remains unchanged for existing users
- No database migrations required

## Future Improvements
- Add more specialized prompts for different use cases
- Implement prompt customization interface
- Add prompt performance metrics
- Support for model-specific prompt optimizations

## How to Test
1. Navigate to Settings > Features
2. Select different prompts from the dropdown
3. Test chat functionality with each prompt
4. Verify prompt persistence after page reload
5. Test with different LLM models if available

# Preview 

## GPT4o:

https://github.com/user-attachments/assets/79e71afe-3934-4638-962a-b3651723430f

## qwen 2.5 Coder 32B

https://github.com/user-attachments/assets/5ed3cc93-89c3-42b5-b127-b1489734ffd1

### CODE REVIEW

**Comment by dustinwloring1988** [comment]
@thecodacus My day just got better, cant wait to use this.

**Comment by dustinwloring1988** [comment]
works on windows.

**Comment by thecodacus** [comment]
we need code template import after this. I would like to add starter templates which will super charge the project outputs

**Comment by dustinwloring1988** [comment]
that would take this to the next level.

**Comment by wonderwhy-er** [comment]
But can't we already use them with github import?
Like here is bolt.new starters
https://boltstarter.com/

It has link like this
https://bolt.new/github.com/donvito/bolt-admin-dashboard

In reality its this repo
https://github.com/donvito/bolt-admin-dashboard


I just go to bolt.diy and import git 
It took a bit of time but I got this
image

Bolt.new works faster for this for some reason
But it does work with bolt.diy

**Comment by thecodacus** [comment]
> But can't we already use them with github import?

yes but thats manual selection. I am talking about 
```
user: i want a todo app
llm: selects vite starter templates and start the project
```

another scenario 
```
i want to design an admin dashboard with schadcn ui and typescript 
llm: selects schadcn starter templates and start the project
```

basically based on user's qurey it should select the best starter template and start.

**Comment by thecodacus** [comment]
> Bolt.new works faster for this for some reason

cuz they are not cloning it using browser resources 😅

**Comment by wonderwhy-er** [comment]
> > Bolt.new works faster for this for some reason
> 
> cuz they are not cloning it using browser resources 😅

Even if they were pulling on server side and then streaming it to client it would be the same no?
May be only part I can imagine is being isomorphic git not being good.

Another is some form of caching they may be do.

**Comment by wonderwhy-er** [comment]
> > But can't we already use them with github import?
> 
> yes but thats manual selection. I am talking about
> 
> ```
> user: i want a todo app
> llm: selects vite starter templates and start the project
> ```
> 
> another scenario
> 
> ```
> user: i want to design an admin dashboard with schadcn ui and typescript 
> llm: selects schadcn starter templates and start the project
> ```
> 
> basically based on user's qurey it should select the best starter template and start.
> 
> currently lots of users are saying they are not getting good results compared to bolt.new this is the reason. for any general query bolt/new is first pulling a suitable starter template, then starting the work

I guess you mean dozen of templates for various setups than? That are very barebone? Like next.js starter, vue starter and so on?

**Comment by thecodacus** [comment]
> I guess you mean dozen of templates for various setups than? That are very barebone? Like next.js starter, vue starter and so on?

Yes exactly. it should have most of the skeleton ready. so that the llm does not have to write them. and the result will instantly become pretty nice

**Comment by thecodacus** [comment]
> May be only part I can imagine is being isomorphic git not being good.

yes isomorphic-git is trying to do an actual git operation in browser, and using a simulated  file system plus  it also needs to get loaded and initialized, where as they are using github api it to pull all the files directly and them pushing it.. both has its pros and cons.

**Pull request merged**
