### PR TITLE
Feat: Basic file tree context menu

### PR DESCRIPTION
**Pull request by kochrt**
Just `Copy path` and `Copy relative path` to start. Lays the groundwork for other context menu options (rename, delete, etc.)

https://github.com/user-attachments/assets/828a0c91-9192-4187-9aa4-284d280850a5

### CODE REVIEW

**Comment by dustinwloring1988** [comment]
Work on Windows

@kochrt great job, look nice and works smooth

**Comment by thecodacus** [comment]
the issue with current system is that when you reload a project it can only reload the project through the chat history. so any changes that doesn't happen through chat history will not be permanent after reload. 

once we figure out a way to fix that these features cannot be merged. 

but yes great work anyway 👍

**Comment by kochrt** [comment]
@thecodacus This PR doesn't deal with any file changing, it's just to copy the path of a file or directory. No state is being edited so there aren't any changes to be saved.

**Comment by thecodacus** [comment]
Ohh.. yess I missed that. let me review and test it, and will merge soon

**Comment by thecodacus** [comment]
Looks good merging it

**Pull request merged**
