### PR TITLE
feat: upload files or folders to chat from local

### PR DESCRIPTION
**Pull request by muzafferkadir**
# Uploading File Integration for AI Chat Interactions

## Features Added
- Added ability to upload local files directly into the chat interface
- Added support for uploading entire folders with multiple files
- Integrated file contents seamlessly into the chat history
- Real-time parsing and display of uploaded files in the workbench

## Technical Implementation
- Implemented `addCustomFile` and `addCustomFolder` functions in Chat.client.tsx
- Added new UI buttons in EditorPanel.tsx for file and folder uploads
- Extended workbench store to handle new file operations
- Files are stored with unique IDs and properly formatted for chat display

## UI Changes
- New "Upload File" button with file upload icon
- New "Upload Folder" button with folder plus icon
- Intuitive file selection interface using native file picker

## Benefits
- Enables users to directly manipulate project files through chat interface
- Streamlines workflow for adding multiple files simultaneously
- Maintains chat history with uploaded file contents
- Improves project collaboration capabilities

## How to Use
1. Click "Upload File" to add a single file
2. Click "Upload Folder" to add multiple files from a directory
3. Files appear in chat history and workbench for AI interaction
4. Make changes through chat interface as needed

This PR enhances the project's functionality by allowing seamless integration of local files into the AI chat workflow, making it more powerful and user-friendly.

### CODE REVIEW

**Comment by muzafferkadir** [comment]
It may be good to add some security measures such as file type restrictions, size limits and node_modules filtering before merging to make it production-ready. It would be good to test thoroughly for potential bugs and edge cases.

**Comment by cepicdalim** [comment]
Same #31

**Comment by muzafferkadir** [comment]
> Same #31 

Ah, after the message you sent, I understood that the pr request was about "downloading files locally" and that the pr request would be cancelled. Are you sure that this pr and 31 are the same? I see that they are different in terms of functionality. If we are sure, we can send any pr request, we can add the missing parts, no problem.

**Comment by twestpqh** [comment]
A much needed feature. Looking forward to when this is available. Hopefully, sooner rather than later.

**Comment by pjmartorell** [comment]
To avoid passing sensitive to the LLM it would be better to exclude files and folders defined in the `.gitignore` (if any)

**Comment by lassecapel** [comment]
I think we need a combination of this pr, #31 and #289. Combining those will add functionality:

- upload for file and folder
- add the context to the chat
- some snity checking on files, don't add the world to the context

**Comment by wonderwhy-er** [comment]
Considering there is now folder import and github public repo import

Does this PR has something that missing there?

**Pull request closed without merging**
