### PR TITLE
Fix: order of execution of the commands and files created must be sequential

### PR DESCRIPTION
**Pull request by ub-dev-7**
Fix to enforce sequential order of execution of the "Run command", ahead of file creation to provide better control over when and where the files are created.  Also, resolved a couple of race conditions between command runs by building a 500ms delay after command executions to allow the OS to commit resources when installing dependencies and writing or modifying files.

### CODE REVIEW

**Comment by wonderwhy-er** [comment]
Hm, why 500? 
Why remove awaits?
Seems like that creates race condition no?

**Comment by thecodacus** [comment]
not sure how this helps, and don't see the issue that is described in the description. please attach a video of the issue you are trying to fix, or if you have a issue number

**Comment by thecodacus** [comment]
okay so I understands the issue you are trying to fix here. the problem here is that the later commands are catching the status code from previous execution and marking that command as finished. its an issue with bolt shell component  osc code handling.
I believe the fix can be applied by only updating that class alone as thats the component handling all the command sequences.

but removing await from the action runner looks like its solves the immediate problem but it introduces other problem that was addressed before. like:
* in your video, fix shows the `start command` was marked as completed where it was actually still running
* have you tested with multiple chats and project reload scenarios

can you also send us the chat export so we can test the issue.

**Comment by ub-dev-7** [comment]
I see your point regarding unintended consequences to removing await.  I can keep it locally for now while try and hunt to fix the commands catching the status code from the previous executions.  My chat history won't serve you well as I've been rearchitecting the prompts.ts file and it's in flux.  But I'll try and get something to help with the testing and reproduction of the issues.

One note though: the interrupt causes more problems since it's not specific to the start commands.  It's interrupting run commands as well when there are many.  The prompts.ts instructs connecting the run commands with && so this issue is masked and only shows up when there are multiple boltActions not joined by &&.

I suggest we table this PR for now to refine the solution.  We may want to capture the issue(s) though. I believe there are 2 for this case:
- the interrupt intended for start commands is tripping the run commands
- the commands catching the status code from the previous executions

**Comment by thecodacus** [comment]
> One note though: the interrupt causes more problems since it's not specific to the start commands. It's interrupting run commands as well when there are many. The prompts.ts instructs connecting the run commands with && so this issue is masked and only shows up when there are multiple boltActions not joined by &&.

if you see the current pipeline run commands gets executed in sequences because of the await.. but the start command is not awaited. so until one run command is finished it will not execute another one. 

so only when an existing start command is already running and we have another run command or a start command getting queued, the interrupt is actually going to work. ( Thats the ideal scenario, but as you see we have the osc code issue right now)

this is what i am saying
image

**Comment by thecodacus** [comment]
@ub-dev-7 , proposing this #789 , can you try it, its working in my cases but i would like to see it run against your chat

**Comment by ub-dev-7** [comment]
#789 failed during my test, but you should test it in case I missed something.

Here's how you can reproduce to see both the interrupt and possibly the race condition:

1) add the following example to prompts.ts and then 2) issue the command: Build a todo app in Angular 

  <example>
    <user_query>Create a hello world angular application</user_query>

        <assistant_response>
          Certainly! I'll create a hello world angular application. 

      <boltArtifact id="angular-app-creation" title="Angular Application Creation with Best Practices">
      <boltAction type="shell">
        npx --yes @angular/cli@latest new hello-world-app --no-create-application --interactive=false --skip-git=true --ssr=false && cd hello-world-app
      </boltAction>

      <boltAction type="shell">
        npx --yes -p @angular/cli@latest ng generate app hello-world --interactive=false --experimental-zoneless=true --style=scss --routing=true --inline-template=true --inline-style=true --skip-tests=true
      </boltAction>

      <boltAction type="shell">
        npx -v 
      </boltAction>

      
      <boltAction type="shell">
        npm install bulma@latest
      </boltAction>

      
      <boltAction type="shell">
        npm install @ngrx/signals@latest @ngrx/entity@latest --force
      </boltAction>

      <boltAction type="file" filePath="hello-world-app/projects/hello-world/src/app/app.component.ts">
        import { Component } from '@angular/core';
        import { inject } from '@angular/core';
        import { RouterOutlet } from '@angular/router';

        @Component({
          imports: [RouterOutlet],
          selector: 'app-root',
          template: \`
            <router-outlet></router-outlet>
          \`,
          styles: []
        })
        export class AppComponent {
          title="Hello World";
        }
      </boltAction>

      <boltAction type="start">
        npm run start
      </boltAction>
    </boltArtifact>

     
      The hello world application is created.  Would you like to add features to it?
    </assistant_response>
  </example>

**Comment by thecodacus** [comment]
Hi @ub-dev-7 , this is working in my setup.
can you check if the 

https://www.youtube.com/watch?v=5wgrOUj8PT8

**Comment by ub-dev-7** [comment]
Tested the https://github.com/stackblitz-labs/bolt.diy/pull/789 branch/PR.
It worked as intended on mac os.  Let's close out this PR in favor of https://github.com/stackblitz-labs/bolt.diy/pull/789

**Pull request closed without merging**
