### PR TITLE
 MODEL_LIST is not accessible in server context so remove check

### PR DESCRIPTION
**Pull request by justindressler**
Fix warning on sass compiler,
MODEL_LIST is not accessible in server context so remove check
Add vs code debug config since most users are using vs code these days
Ignore package-lock.json in case contributor uses NPM instead of PNPM due to crazy windows privileged issues.

NOTE: Only change needed to function is in 
app/lib/.server/llm/stream-text.ts

But i made the other changes to clean up NPM and build warnings

### CODE REVIEW

**Comment by justindressler** [comment]
fixes issue #249

**Comment by coleam00** [comment]
Thanks for these updates @justindressler! Think you could split the MODEL_LIST fix into a separate PR from the other config changes?

**Comment by justindressler** [comment]
Sure thing. BTW what model do you recommend I tried ollama qwen2.5-coder:7b I had some success but the model wasn't generating fully formatted code. I think the 7b is the biggest I can run the 14b require 4 bit quants which is marginal I prefer 5 bit and up quants. But it did generate a basic project so that is something :)

The PNPM package manager on Windows was giving me alot of headaches I suggest you switch to Yarn or just plain NPM. For open source NPM might be better no one needs to install yarn then.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by thecodacus** [comment]
> MODEL_LIST is not accessible in server context so remove check

I don't think this is right, server can access MODEL_LIST.
can you specify the problem you are trying to fix ?

**Comment by justindressler** [comment]
Im going to retract the pull request i have merged the latest changes and the problem has returned. 
`APICallError [AI_APICallError]: Not Found
    at D:\bolt.new-any-llm\node_modules\.pnpm\@ai-sdk+provider-utils@1.0.20_zod@3.23.8\node_modules\@ai-sdk\provider-utils\src\response-handler.ts:72:16
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at postToApi (D:\bolt.new-any-llm\node_modules\.pnpm\@ai-sdk+provider-utils@1.0.20_zod@3.23.8\node_modules\@ai-sdk\provider-utils\src\post-to-api.ts:81:28)
    at OllamaChatLanguageModel.doStream (D:\bolt.new-any-llm\node_modules\.pnpm\ollama-ai-provider@0.15.2_zod@3.23.8\node_modules\ollama-ai-provider\src\ollama-chat-language-model.ts:230:50)
    at fn (file:///D:/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@5.4.0__svelte@5.4.0_vue@3.5.13_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/generate-text/stream-text.ts:378:23)
    at file:///D:/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@5.4.0__svelte@5.4.0_vue@3.5.13_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/telemetry/record-span.ts:18:22
    at _retryWithExponentialBackoff (file:///D:/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@5.4.0__svelte@5.4.0_vue@3.5.13_typescript@5.7.2__zod@3.23.8/node_modules/ai/util/retry-with-exponential-backoff.ts:37:12)
    at startStep (file:///D:/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@5.4.0__svelte@5.4.0_vue@3.5.13_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/generate-text/stream-text.ts:333:13)
    at fn (file:///D:/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@5.4.0__svelte@5.4.0_vue@3.5.13_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/generate-text/stream-text.ts:414:11)
    at file:///D:/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.33_react@18.3.1_sswr@2.1.0_svelte@5.4.0__svelte@5.4.0_vue@3.5.13_typescript@5.7.2__zod@3.23.8/node_modules/ai/core/telemetry/record-span.ts:18:22
    at chatAction (D:/bolt.new-any-llm/app/routes/api.chat.ts:73:20)
    at Object.callRouteAction (D:\bolt.new-any-llm\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\data.js:36:16)
    at D:\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4899:19
    at callLoaderOrAction (D:\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4963:16)
    at async Promise.all (index 0)
    at defaultDataStrategy (D:\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4772:17)
    at callDataStrategyImpl (D:\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4835:17)
    at callDataStrategy (D:\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3992:19)
    at submit (D:\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3755:21)
    at queryImpl (D:\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3684:22)
    at Object.queryRoute (D:\bolt.new-any-llm\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:3629:18)
    at handleResourceRequest (D:\bolt.new-any-llm\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:402:20)
    at requestHandler (D:\bolt.new-any-llm\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\server.js:156:18)
    at D:\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_3djlhh3t6jbfog2cydlrvgreoy\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:70:25 {
  cause: undefined,
  url: 'http://localhost:11434/api/chat',
  requestBodyValues: {
    format: undefined,
    model: 'claude-3-5-sonnet-latest',
    options: { num_ctx: 32768, num_predict: 8000, temperature: 0 },
    messages: [ [Object], [Object] ],
    tools: undefined
  },
  statusCode: 404,
  responseHeaders: {
    'content-length': '78',
    'content-type': 'application/json; charset=utf-8',
    date: 'Sat, 14 Dec 2024 06:09:12 GMT'
  },
  responseBody: '{"error":"model \\"claude-3-5-sonnet-latest\\" not found, try pulling it first"}',
  isRetryable: false,
  data: undefined,
  [Symbol(vercel.ai.error)]: true,
  [Symbol(vercel.ai.error.AI_APICallError)]: true
}`

this is the output i get when selecting Ollama and qwen2.5-coder the code above originally fixed this problem but it has returned the problem in the selected model is not sent to ollama. Instead of 'claude-3-5-sonnet-latest' it should be 'qwen2.5-coder' as selected in the front end i don't have time to trouble shoot the new issue. Maybe later

**Comment by thecodacus** [comment]
yes I have seen this issue, this was because server was not able get the dynamic model's list. 
i think it is now fixed in a PR @dustinwloring1988 did to get the dynamic model's list working

can you just check once and see if you are still seeing this issue ?

**Comment by justindressler** [comment]
Yep it does seem to work now using latest code main branch. I think there was something strange initially were Ollama and the model was selected but the dropdown under chat had the claude model. But after refresh of browser it worked. I can get coder to write one of the sample apps but the version im running isn't vary smart 🙁

________________________________

**Pull request closed without merging**
