### PR TITLE
Add web browsing feature to LLM

### PR DESCRIPTION
**Pull request by ed23x**
Related to #326

---

For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/coleam00/bolt.new-any-llm/pull/327?shareId=3c40d2c2-775e-4384-9d8f-a0dbda8d757f).

### CODE REVIEW

**Comment by wonderwhy-er** [comment]
How does this work exactly?
I guess headless chrome is running on server and allows to use duckduck go to search internet.
But how exactly calls to it are sent and get back in to the chat?

**Comment by kustomzone** [comment]
Swy, not sure if this is a partial or complete PR?

Needs `npm install playwright` or add it to `package.json`.
The import `getWebBrowsingModel` added to `api.chat.ts` is not used.
And `api.chat.ts` is throwing `Expected ',', got 'ActionFunctionArgs'` in it's current state.

**Comment by chrismahoney** [comment]
We should have the GH workflow issues ironed out, it should simply require approval from a Contributor member and no conflicts with main.

That being said, this is a **large** feature and it may be better served with placement on the upcoming roadmap. I would love to have this as well, but running Chromium should be considered for any issues related to security or support/maintenance.

**Comment by wonderwhy-er** [comment]
I converted it to draft for now

**Comment by ed23x** [comment]
yo im not sure it works. ive seen it in devika or opendevin that browsing feature. this was my first isue so idk what im doin

**Comment by wonderwhy-er** [comment]
Closing for now as it stalled

**Pull request closed without merging**
