### PR TITLE
feat: Add importing from github

### LINKED ISSUE #323: Option to import github repository similar to the cloud environment
Option to import github repository similar to the cloud environment:
https://bolt.new/~/github.com/vinodsharma10x/saas-founder-hub

http://localhost:5173/~/github.com/vinodsharma10x/saas-founder-hub

When I try I get a 404 not found error.

I really need a way to import my projects, as it became unfeasible to continue with the bolt.new plan.

### PR DESCRIPTION
**Pull request by kochrt**
https://github.com/user-attachments/assets/3be63a72-252a-490f-9c96-a5026f7cdaab

Fixes #323 

Similar to how bolt.new does it, you can either append a github url to the path (localhost:5174/github.com/owner/repo) or you can import via dialog. Downloads files client side.

Works for public repositories.

### CODE REVIEW

**Comment by thecodacus** [comment]
Why does it utilise the action runner and have updated section in artifact component when this does not use any actions provided by the llm 

plus does it provide the context to llm on what has been imported?

**Comment by kochrt** [comment]
Thanks for taking a look @thecodacus - I was trying to get the same effect bolt.new has when importing a project (it shows up as an artifact in chat) but never really got it. I'll revert those parts. 

> does it provide context to llm on what has been imported

No... how do I do that?

**Comment by kustomzone** [comment]
See @burgil's [fork](https://github.com/burgil/bolt.new-any-llm_windows)

https://github.com/coleam00/bolt.new-any-llm/issues/390#issuecomment-2495990322

**Comment by kochrt** [comment]
👍  I'll take a look

**Comment by cetinmustafa83** [comment]
https://github.com/FurkannM/bolt.new-extended

I found someone who added features like adding files, should we clone their features?

**Comment by kustomzone** [comment]
> I found someone who added features like adding files, should we clone their features?

It's been [pending](https://github.com/coleam00/bolt.new-any-llm/pull/31) for a month.
I added Files and Folder separately as it let's one choose a specific collection of files.
But it's currently missing the context hack that @Burgil added yesterday, which is required to persist the imports.

**Comment by wonderwhy-er** [comment]
I just submited PR for review that allows exporting/importing chats.
In my list next is importing folders to start a new chat.
Will probably do a PR in the morning.

After that its github work unless someone does a good one before.
But without foundational work to import folders jumping to github imports is larger jump.

**Comment by wonderwhy-er** [comment]
We do need to start to put in work of working with github APIs
I proposed elsewhere to introduce server side calls that allow oauth with github and store tokens in JWT tokens.
So we can have users logged in and pulling and pushing from github with their own account. 
Without us requiring the to introduce a server side database/persistance 

Here is thread on community with more details https://thinktank.ottomator.ai/t/idea-for-github-oauth-access/624

**Comment by Toddyclipsgg** [comment]
@kochrt How do I put it in my repository?

**Comment by dustinwloring1988** [comment]
I agree with @thecodacus also this now has conflicts can you please update this?

**Pull request closed without merging**
