### PR TITLE
feat: Add GLHF Models Provider Integration

### PR DESCRIPTION
**Pull request by ThePsyberSleuth**
# PR Description

This PR adds support for GLHF Models to the oTToDev platform.

## Changes

- Added GLHF Models provider configuration in `constants.ts`
- Updated `README.md` to include GLHF Models in the supported providers list
- Fixed TypeScript and linting issues in `action-runner.ts`
- Added proper error handling for GLHF API integration
- Added comprehensive documentation for GLHF Models setup and usage

## Documentation Updates

- Added GLHF Models to the list of supported providers in `index.md`
- Added detailed GLHF Models description and setup instructions in `CONTRIBUTING.md`
- Added environment variable documentation for GLHF API key

## GLHF Models Overview

GLHF.chat is a powerful and flexible LLM service that enables users to run virtually any Hugging Face model with minimal setup. The service features:
- Universal support for Hugging Face models
- Advanced GPU infrastructure with up to 8 Nvidia H100 80GB GPUs
- Custom GPU scheduler with vLLM technology
- Automatic resource provisioning and scaling
- Model fine-tuning capabilities
- Cost-effective multi-tenant infrastructure

## Testing

- Verified GLHF Models appear in the provider selection
- Tested API integration with proper error handling
- Ensured TypeScript types are properly maintained
- Confirmed all linting rules pass

## Requires

- `GLHF_API_KEY` environment variable for accessing GLHF Models

## Contributors

- @ThePsyberSleuth

## Related Issues

None

### CODE REVIEW

**Comment by ThePsyberSleuth** [comment]
> @ThePsyberSleuth is this a dub if so please close one: https://github.com/coleam00/bolt.new-any-llm/pull/485

Hi @dustinwloring1988 please can you explain to me what you're talking about as this is my first time contributing to a project.

**Comment by dustinwloring1988** [comment]
please see this link: https://github.com/coleam00/bolt.new-any-llm/pull/485

**Comment by ThePsyberSleuth** [comment]
> please see this link: https://github.com/coleam00/bolt.new-any-llm/pull/485

Thanks @dustinwloring1988 just closed the other PR

**Comment by dustinwloring1988** [comment]
@ThePsyberSleuth please fix the conflicts so we can look at it

**Comment by ThePsyberSleuth** [comment]
> @ThePsyberSleuth please fix the conflicts so we can look at it

@dustinwloring1988 Just resolved all conflicts please review

**Comment by akrmba** [comment]
Thanks

**Comment by ThePsyberSleuth** [comment]
> Thanks

Most welcome

**Comment by dustinwloring1988** [comment]
Thanks for the update but in the drop down for the provider it show 2 (GitHub Models and GLHF, is this intended):

**Comment by ThePsyberSleuth** [comment]
> Thanks for the update but in the drop down for the provider it show 2 (GitHub Models and GLHF, is this intended):
> 
> 

Yes

**Comment by andreclemente** [comment]
Hey, was this pull request merged? I think we're still missing GLHF

**Pull request closed without merging**
