### PR TITLE
feat: added settings modal and saving keys/base URL from UI

### PR DESCRIPTION
**Pull request by Periskulum**
SettingsModal
Settings Icon Location

This pull request introduces a settings modal that allows you to save API Keys, Base URL's and default model/providers to localStorage via the chat UI.

### Settings Management:
* **Settings Modal Implementation**: Added a new `SettingsModal` component to manage API keys, base URLs, and default provider/model dynamically. (`app/components/chat/SettingsModal.tsx`)
* **Settings UI Update**: Updated the `BaseChat` component to include a settings button that opens the settings modal, allowing users to manage their settings without restarting the application. (`app/components/chat/BaseChat.tsx`) [[1]](diffhunk://#diff-a87a7f7c69d4bc6518b70a4fa3122ede18e570da15f12975804a87eac181c700R107-R116) [[2]](diffhunk://#diff-a87a7f7c69d4bc6518b70a4fa3122ede18e570da15f12975804a87eac181c700R162-R172) [[3]](diffhunk://#diff-a87a7f7c69d4bc6518b70a4fa3122ede18e570da15f12975804a87eac181c700R221-R227) [[4]](diffhunk://#diff-a87a7f7c69d4bc6518b70a4fa3122ede18e570da15f12975804a87eac181c700R284-R294)

### Provider and Model Selection:
* **Dynamic Provider List**: Modified the `ModelSelector` component to dynamically include additional providers (`Ollama` and `OpenAILike`) if they are not already present in the `MODEL_LIST`. (`app/components/chat/BaseChat.tsx`) [[1]](diffhunk://#diff-a87a7f7c69d4bc6518b70a4fa3122ede18e570da15f12975804a87eac181c700L25-R36) [[2]](diffhunk://#diff-a87a7f7c69d4bc6518b70a4fa3122ede18e570da15f12975804a87eac181c700L45-R53)
* **Provider and Model State Management**: Updated the `BaseChat` and `Chat.client` components to load and save the selected provider and model from localStorage, ensuring persistence across sessions. (`app/components/chat/BaseChat.tsx`, `app/components/chat/Chat.client.tsx`) [[1]](diffhunk://#diff-a87a7f7c69d4bc6518b70a4fa3122ede18e570da15f12975804a87eac181c700R107-R116) [[2]](diffhunk://#diff-c3e814ea52016b5a6aa549d4a1b89d306c9ac276ba0f79a956dba166e6c84b09R102-R107) [[3]](diffhunk://#diff-c3e814ea52016b5a6aa549d4a1b89d306c9ac276ba0f79a956dba166e6c84b09R207-R208) [[4]](diffhunk://#diff-c3e814ea52016b5a6aa549d4a1b89d306c9ac276ba0f79a956dba166e6c84b09L185-R233)

### API Key Management:
* **Stored Credentials Helper**: Added a helper function to retrieve stored API keys and base URLs from localStorage, ensuring these credentials are included in requests. (`app/components/chat/Chat.client.tsx`)
* **Settings Modal Logic**: Implemented logic in the `SettingsModal` component to load, save, and clear API keys and base URLs, providing a user-friendly interface for managing these settings. (`app/components/chat/SettingsModal.tsx`)

### Documentation Update:
* **README.md Changes**: Updated the documentation to include information about the new settings management feature, guiding users on how to configure API keys and other settings via the UI. (`README.md`) [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R86) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R129-R130)

### Other Notes:
* **Needs More Testing**: This feature has been tested in a browser using localStorage and the .env.local file, but I was unable to test with all AI APIs due to lack of access. Additionally, I do not currently have a PC that I can run Docker on, so containerized testing hasn't been done. While the implementation works as intended, there are most certainly more elegant approaches, and further testing in different environments is recommended.

### CODE REVIEW

**Comment by thecodacus** [comment]
nice work.. this one is much needed feature.. but I believe having a separate dedicated page for all these configurations would be better

**Review by chrismahoney — COMMENTED** [review]
@coleam00 This looks good on my end with the API key coming into local providers, would you be able to test it with OpenAI/Anthropic/any other one to ensure it works non-local? If so I am 👍

**Comment by chrismahoney** [comment]
One consideration, although local storage is generally a safe place for the keys is that we may want to encrypt them now or later.

**Comment by coleam00** [comment]
This looks fantastic @Periskulum, nice work!

@chrismahoney I saw you merged a similar pull request, are these too similar or what you do think?

**Comment by chrismahoney** [comment]
I like this approach versus the inline key entry from #101 which I merged, and I would have preferred this solution but was getting some failures on the GitHub Action run. I’d suggest we hide the inline key field I merged and utilize this instead as the start of a general settings modal. Thoughts?

**Comment by coleam00** [comment]
@chrismahoney I agree with you here!

**Comment by Periskulum** [comment]
Hey thanks for the feedback guys, I've been meaning to make some more tweaks to get things smoother but I've been dealing with a family emergency so I havent had time to address or update anything really. Let me know if you guys have any questions and I'll answer where I can though.

**Comment by chrismahoney** [comment]
No worries, I think since I merged the previous solution in before this, I can take some time soon to get this merged against current main. Take care of yourself and thanks again 🙌

**Comment by wonderwhy-er** [comment]
May be one more issue I see, you list all settings and providers at all times
That is suboptimal as we will be getting more and more. 

In that sense I kinda like current merged inline solution where you pick provider and see settings related only to it like urls and api keys and possibly other things.

**Comment by coleam00** [comment]
That's good feedback @wonderwhy-er! What are your thoughts @Periskulum? Also please take your time, I hope things are okay for you and your family!

**Comment by Periskulum** [comment]
@wonderwhy-er I agree hat is actually something I did want to address by having the list only show an initial default option with a drop down to select a provider and area to enter the key. Then just have a plus button to add more provider/api key combos as needed and would even allow for adding multiple keys from the same provider, like the Openai Like keys for example. This way the UI would only ever show the ones the user has added /needs

**Comment by thecodacus** [comment]
implemented a different settings modal, but thanks for looking into this, much appreciated

**Pull request closed without merging**
