### PR TITLE
feat: add chat history backup and restore functionality

### PR DESCRIPTION
**Pull request by sidbetatester**
This PR adds chat history backup and restore functionality, continuing the work from #280.

Changes include:
- Enhanced chat import with support for multiple formats:
  - Standard Bolt format
  - Chrome extension IndexedDB backup format
  - History array format
- Improved validation and error handling
- Added user feedback via toast notifications
- Updated README to reflect the new feature

Note: After the #280 commits, the structure of bolt has significantly changed, so in this commit, I only introduced what you missed including from my previous commit and must not have any conflicts. 

Previous feedback addressed:
1. Fixed TypeScript issues
2. Improved error handling and validation
3. Added proper success messages
4. Cleaned up code organization

Reference: This continues the work from #280 which was accidentally closed during branch reorganization.
https://github.com/stackblitz-labs/bolt.diy/pull/280

### CODE REVIEW

**Comment by sidbetatester** [comment]
Hi Anirban @thecodacus
I cleaned up the code to match latest version, we should not have any conflicts now. Can you verify and approve.

**Comment by thecodacus** [comment]
> Hi Anirban @thecodacus I cleaned up the code to match latest version, we should not have any conflicts now. Can you verify and approve.

I have added my reviews. I just noticed that you are using your main branch to raise PR, Please read the contribution guidelines [here ](https://stackblitz-labs.github.io/bolt.diy/CONTRIBUTING/), and use a feature branch for the PR. else any changes to your main will automatically be reflected to this PR which can be problematic.

**Comment by sidbetatester** [comment]
> > Hi Anirban @thecodacus I cleaned up the code to match latest version, we should not have any conflicts now. Can you verify and approve.
> 
> I have added my reviews. I just noticed that you are using your main branch to raise PR, Please read the contribution guidelines [here ](https://stackblitz-labs.github.io/bolt.diy/CONTRIBUTING/), and use a feature branch for the PR. else any changes to your main will automatically be reflected to this PR which can be problematic.

thank you, acknowledged, I did follow the CONTRIBUTING.md the first time, should have remembered to do that same. I was using windsurf for my edits and commits.

**Comment by sidbetatester** [comment]
@thecodacus , @wonderwhy-er 
Hey Guy, 
Is there anything pending from me, just making sure.

**Comment by wonderwhy-er** [comment]
@sidbetatester can you add video or screenshots to show how its used
Otherwise will review now

**Comment by wonderwhy-er** [comment]
Just checked.
Couple of things:
1. Icons seem too big and out of place
image


2. You solved conflicts with master in wrong way so that you lost gearbox that opens settings in bottom left corner
master version:
Screenshot 2024-12-28 at 11 04 13

your version:
Screenshot 2024-12-28 at 11 04 03


3. There is now chat history section in settings that has export all chats but not import chats
May be you can add it there instead, not sure
image

**Comment by sidbetatester** [comment]
@wonderwhy-er  thank you for the detailed feedback. I understood what happened when I merged from the main instead of a feature branch.. 
To avoid such confusion, I created a new PR from the feature branch: 
https://github.com/stackblitz-labs/bolt.diy/pull/936

I will close this PR.

**Pull request closed without merging**
