### PR TITLE
feat: add URL input component for converting URLs to markdown

### PR DESCRIPTION
**Pull request by dazeb**
A simple feature that will download any page as markdown instantly.

The markdown file is automatically downloaded after the url has been submit.

This uses Jina.ai Reader. No need for API key, the free tier is more than enough to download web pages for a single user.

 
download

### CODE REVIEW

**Comment by thecodacus** [comment]
nice concept but feels like it a websearch plugin or something, confusing to the user

**Comment by wonderwhy-er** [comment]
Yeah that sounds more like "import website".
I wonder how this will perform with hosted versions.
Need to test.
Would importing website with all js/html/css not work better? I mean in markdown form it probably looses styling?

**Comment by thecodacus** [comment]
Weird, I did merge this but still says its merged with another PR I just merged

**Comment by thecodacus** [comment]
Okay..  so because its raised from the main branch and that is then reset. I guess we will stop accepting PRs from main branch, and make that as a hard rule

**Pull request merged**
